-- I-HUB : chambres d'hospitalisation configurées en base de données.
-- Les identifiants 1..10 sont conservés pour correspondre aux hospitalisations
-- déjà enregistrées lorsque les chambres étaient définies dans le code.
CREATE TABLE IF NOT EXISTS hospital_rooms (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  room_number TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  service TEXT NOT NULL DEFAULT 'general',
  type TEXT NOT NULL DEFAULT 'standard',
  total_beds INTEGER NOT NULL CHECK (total_beds > 0),
  daily_rate NUMERIC NOT NULL DEFAULT 0 CHECK (daily_rate >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO hospital_rooms (id, room_number, label, service, type, total_beds, daily_rate)
VALUES
  (1, 'A1', 'Chambre A1', 'maternite', 'standard', 6, 15),
  (2, 'A2', 'Chambre A2 — VIP', 'maternite', 'vip', 1, 25),
  (3, 'A3', 'Chambre A3 — VIP', 'maternite', 'vip', 1, 25),
  (4, 'A4', 'Chambre A4 — VIP', 'maternite', 'vip', 1, 25),
  (5, 'B1', 'Chambre B1', 'general', 'standard', 6, 15),
  (6, 'B2', 'Chambre B2', 'general', 'standard', 3, 20),
  (7, 'B3', 'Chambre B3', 'general', 'standard', 3, 20),
  (8, 'B4', 'Chambre B4 — VIP', 'general', 'vip', 1, 25),
  (9, 'B5', 'Chambre B5 — VIP', 'general', 'vip', 1, 25),
  (10, 'B6', 'Chambre B6 — VIP', 'general', 'vip', 1, 25)
ON CONFLICT (id) DO UPDATE SET
  room_number = EXCLUDED.room_number, label = EXCLUDED.label,
  service = EXCLUDED.service, type = EXCLUDED.type,
  total_beds = EXCLUDED.total_beds, daily_rate = EXCLUDED.daily_rate,
  updated_at = NOW();

SELECT setval(pg_get_serial_sequence('hospital_rooms', 'id'),
              GREATEST((SELECT COALESCE(MAX(id), 1) FROM hospital_rooms), 1));
