-- I-HUB : exécuter une seule fois dans Supabase > SQL Editor.
CREATE TABLE IF NOT EXISTS public.cash_closures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closure_date DATE NOT NULL,
    closed_by_id BIGINT,
    closed_by_name TEXT,
    physical_cash_usd NUMERIC(14,2) NOT NULL DEFAULT 0,
    physical_cash_cdf NUMERIC(18,2) NOT NULL DEFAULT 0,
    notes TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'closed',
    closed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT cash_closures_one_per_day UNIQUE (closure_date)
);

CREATE INDEX IF NOT EXISTS idx_cash_closures_date
    ON public.cash_closures (closure_date DESC);
